name: News Scraper

on:
  schedule:
    - cron: '0 13,19 * * *'  # Runs at 1 PM and 7 PM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run database setup
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python database_setup.py
    
    - name: Run news scraper
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python news_scraper.py
    
    - name: Run bot update
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python main.py