name: Run Main Script

on:
  workflow_run:
    workflows: ["Run Telegram Scraper"]
    types:
      - completed

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for 2 minutes
      run: sleep 120
    - name: Run main script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python main.py